name: Push Feed Data to Drupal

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: install https
        run: npm install -g https
      - name: post data to drupal
        run: node ../.github/scripts/test.js
